import { describe, it, expect } from "vitest";
import { readFileSync } from "node:fs";
import { join } from "node:path";
import { generatePlan } from "@/lib/plan-generator";
import type { Intake } from "@/lib/schema";
import { PlanSchema } from "@/lib/schema";

/**
 * Parity test: for each profile, run the TS generatePlan() with the same
 * intake the Python CLI received, then assert the output matches the CLI's
 * `--json` output byte-for-byte.
 *
 * Fixtures are generated by piping the same inputs to:
 *   python3 tools/generate_student_plan.py --json
 *
 * If this test fails, EITHER the TS port has drifted OR the CLI has changed
 * and fixtures need regeneration. Investigate the diff before deciding.
 */

interface ParityCase {
  fixture: string;
  intake: Intake;
}

const CASES: ParityCase[] = [
  {
    fixture: "maria-10-sgv-stem-csu.json",
    intake: {
      name: "Maria",
      grade: 10,
      gpa: 3.2,
      onlineOnly: false,
      regionId: "3",
      major: "stem",
      target: "csu",
    },
  },
  {
    fixture: "jordan-9-oc-health-uc.json",
    intake: {
      name: "Jordan",
      grade: 9,
      gpa: 3.7,
      onlineOnly: false,
      regionId: "7",
      major: "health",
      target: "uc",
    },
  },
  {
    fixture: "alex-12-inland-business-transfer.json",
    intake: {
      name: "Alex",
      grade: 12,
      gpa: 1.5,
      onlineOnly: false,
      regionId: "10",
      major: "business",
      target: "transfer",
    },
  },
  {
    fixture: "sam-11-online-undecided-undecided.json",
    intake: {
      name: "Sam",
      grade: 11,
      gpa: 2.7,
      onlineOnly: true,
      regionId: undefined,
      major: "undecided",
      target: "undecided",
    },
  },
  {
    fixture: "riley-9-sfv-arts-private.json",
    intake: {
      name: "Riley",
      grade: 9,
      gpa: 2.2,
      onlineOnly: false,
      regionId: "5",
      major: "arts",
      target: "private",
    },
  },
];

const FIXTURE_DIR = join(__dirname, "fixtures", "parity");

function loadFixture(name: string): unknown {
  return JSON.parse(readFileSync(join(FIXTURE_DIR, name), "utf-8"));
}

describe("CLI parity — generatePlan output matches Python CLI --json output", () => {
  for (const c of CASES) {
    it(`parity: ${c.fixture}`, () => {
      const fixture = loadFixture(c.fixture);
      const fixtureParsed = PlanSchema.parse(fixture);
      const plan = generatePlan(c.intake, fixtureParsed.generated_at);

      // The TS port must produce a plan that's structurally and value-identical
      // to the CLI's JSON output. Whole-object deep equality is the strictest
      // possible check.
      expect(plan).toEqual(fixtureParsed);
    });
  }

  it("covers all 7 majors across the fixture set", () => {
    const majors = new Set(CASES.map((c) => c.intake.major));
    // Confirm we exercise enough major diversity (≥5 of 7 covered by fixtures).
    expect(majors.size).toBeGreaterThanOrEqual(5);
  });

  it("covers all 5 targets across the fixture set", () => {
    const targets = new Set(CASES.map((c) => c.intake.target));
    expect(targets.size).toBe(5);
  });

  it("covers all 4 grades across the fixture set", () => {
    const grades = new Set(CASES.map((c) => c.intake.grade));
    expect(grades).toEqual(new Set([9, 10, 11, 12]));
  });

  it("covers all 3 gpa_status values across the fixture set", () => {
    const statuses = new Set(
      CASES.map((c) => {
        const f = PlanSchema.parse(loadFixture(c.fixture));
        return f.student.gpa_status;
      })
    );
    expect(statuses).toEqual(new Set(["alert", "note", "ok"]));
  });

  it("includes one online-only profile and one with online_only=false", () => {
    expect(CASES.some((c) => c.intake.onlineOnly)).toBe(true);
    expect(CASES.some((c) => !c.intake.onlineOnly)).toBe(true);
  });
});
