import { describe, it, expect } from "vitest";
import { readFileSync, readdirSync } from "node:fs";
import { join } from "node:path";
import { PlanSchema } from "@/lib/schema";
import { getCollegeGates, partitionSequence } from "@/lib/course-gates";

/**
 * Guards the dev preview fixtures in tests/fixtures/preview/.
 *
 * These are NOT parity fixtures. They are generated by generatePlan() via
 * `npm run gen-preview-fixtures` purely so the preview route can render
 * layouts the CLI parity set does not cover. This file makes sure they stay
 * valid Plans and keep exercising what they were added to exercise.
 */

const DIR = join(__dirname, "fixtures", "preview");
const files = readdirSync(DIR).filter((f) => f.endsWith(".json"));

function load(name: string) {
  return PlanSchema.parse(JSON.parse(readFileSync(join(DIR, name), "utf-8")));
}

describe("preview fixtures", () => {
  it("has at least one fixture", () => {
    expect(files.length).toBeGreaterThan(0);
  });

  it("every fixture is a valid Plan", () => {
    for (const f of files) expect(() => load(f)).not.toThrow();
  });

  it("covers El Camino, which the parity set does not", () => {
    const colleges = files.map((f) => load(f).college.name);
    expect(colleges).toContain("El Camino College");
  });

  it("the grade-10 fixture actually exercises a blocked course", () => {
    const plan = load("devon-10-southbay-social-csu.json");
    const { blocked } = partitionSequence(
      plan.major_track.sequence,
      getCollegeGates(plan.college.name),
      plan.student.grade,
    );
    expect(blocked.length).toBeGreaterThan(0);
    expect(blocked.map((b) => b.course.course)).toContain("English 1A");
  });

  it("the grade-12 fixture exercises the released state", () => {
    const plan = load("harper-12-southbay-social-csu.json");
    const { blocked } = partitionSequence(
      plan.major_track.sequence,
      getCollegeGates(plan.college.name),
      plan.student.grade,
    );
    expect(blocked).toHaveLength(0);
  });

  it("does not collide with any parity fixture name", () => {
    const parity = readdirSync(join(__dirname, "fixtures", "parity"));
    expect(files.filter((f) => parity.includes(f))).toEqual([]);
  });
});
