import { notFound } from "next/navigation";
import { promises as fs } from "node:fs";
import path from "node:path";
import { PlanSchema } from "@/lib/schema";
import { PlanShell } from "@/components/plan/PlanShell";

// Dev-only preview route. Renders PlanShell from a fixture so the layout can
// be reviewed without Upstash. Disabled in production builds.
//
// Two fixture sources, checked in this order:
//   tests/fixtures/parity/   CLI-generated, the parity contract. Never hand-edit.
//   tests/fixtures/preview/  generated by `npm run gen-preview-fixtures`, for
//                            layouts the parity set does not cover.
//
// Usage:
//   /plan/preview/maria-10-sgv-stem-csu
//   /plan/preview/sam-11-online-undecided-undecided
//   /plan/preview/jordan-9-oc-health-uc
//   /plan/preview/alex-12-inland-business-transfer
//   /plan/preview/riley-9-sfv-arts-private
//   /plan/preview/devon-10-southbay-social-csu    El Camino, gates active
//   /plan/preview/harper-12-southbay-social-csu   El Camino, gates released

export const dynamic = "force-dynamic";

type Props = {
  params: Promise<{ fixture: string }>;
};

export default async function PreviewPlanPage({ params }: Props) {
  if (process.env.NODE_ENV === "production") {
    notFound();
  }
  const { fixture } = await params;

  // Defense in depth — never let a hostile param escape the fixtures dir.
  if (!/^[a-z0-9-]+$/.test(fixture)) {
    notFound();
  }

  const searchDirs = ["parity", "preview"] as const;
  let raw: string | undefined;
  for (const dir of searchDirs) {
    const fixturePath = path.join(
      process.cwd(),
      "tests",
      "fixtures",
      dir,
      `${fixture}.json`,
    );
    try {
      raw = await fs.readFile(fixturePath, "utf8");
      break;
    } catch {
      // Try the next directory.
    }
  }
  if (raw === undefined) {
    notFound();
  }
  const plan = PlanSchema.parse(JSON.parse(raw));
  // Hard-coded sample narrative so the NarrativeBlock styling is visible in
  // dev preview without a live n8n webhook. Production /plan/[shareId]
  // fetches the real narrative from /api/narrative.
  const sampleNarrative = `${plan.student.name}, the play here is straightforward. ${plan.college.name} has one of the strongest dual-enrollment programs in your area, and starting in ${plan.student.grade}th grade gives you real runway. Stack the right courses early and the credit adds up fast.`;
  return (
    <>
      <div className="bg-[#B68D40]/10 border-b border-[#B68D40]/20 text-center py-2 text-xs uppercase tracking-wider text-[#1B4332] font-semibold">
        Dev preview · fixture: {fixture}
      </div>
      <PlanShell plan={plan} initialNarrative={sampleNarrative} />
    </>
  );
}
