/**
 * gen-preview-fixtures.ts — writes dev-only preview fixtures to
 * tests/fixtures/preview/.
 *
 * Run: npm run gen-preview-fixtures
 *
 * WHY THIS IS SEPARATE FROM tests/fixtures/parity/
 * Parity fixtures are generated by the Python CLI and are the contract the
 * TS port is tested against. Nothing may be hand-added there. These preview
 * fixtures are generated by generatePlan() itself, purely so the dev preview
 * route can render layouts the parity set does not cover. They are never
 * compared against the CLI.
 *
 * The parity set has no El Camino student (regions 3, 5, 7, 10 and online),
 * so the El Camino prerequisite gates and ADT routes could not be eyeballed
 * without this.
 */

import fs from "node:fs";
import path from "node:path";
import { generatePlan } from "@/lib/plan-generator";
import { IntakeSchema, PlanSchema, type Intake } from "@/lib/schema";

/** Fixed so regenerating produces no diff unless the generator itself changed. */
const GENERATED_AT = "2026-08-19";

const FIXTURES: Array<{ name: string; intake: Intake }> = [
  {
    // Region 1 is El Camino. Grade 10 so ENGL C1000 is blocked, and the
    // social track exercises the statistics and psychology advisories too.
    name: "devon-10-southbay-social-csu",
    intake: {
      name: "Devon",
      grade: 10,
      gpa: 3.2,
      onlineOnly: false,
      regionId: "1",
      major: "social",
      target: "csu",
    },
  },
  {
    // Same college, grade 12, so the gates release and the block disappears.
    name: "harper-12-southbay-social-csu",
    intake: {
      name: "Harper",
      grade: 12,
      gpa: 3.2,
      onlineOnly: false,
      regionId: "1",
      major: "social",
      target: "csu",
    },
  },
];

const OUT_DIR = path.join(process.cwd(), "tests", "fixtures", "preview");

function main(): void {
  fs.mkdirSync(OUT_DIR, { recursive: true });

  for (const { name, intake } of FIXTURES) {
    const parsedIntake = IntakeSchema.parse(intake);
    const plan = PlanSchema.parse(generatePlan(parsedIntake, GENERATED_AT));
    const target = path.join(OUT_DIR, `${name}.json`);
    fs.writeFileSync(target, `${JSON.stringify(plan, null, 1)}\n`, "utf8");
    console.log(
      `wrote ${name}.json — ${plan.college.name}, grade ${plan.student.grade}, ${plan.major_track.key}`,
    );
  }

  console.log(`\n${FIXTURES.length} preview fixtures written to ${OUT_DIR}`);
}

main();
